### ISSUE TITLE
Adding License for dll

### ISSUE THREAD

**Issue by Harini2019** [intrueder/Control.Draggable#1]
Hello Sir,

Could you please include license in GitHub for Control.Draggable.dll  

Thanks.

**Comment by intrueder** [comment]
Hi @Harini2019 , I've added MIT license file to repo. Does it satisfy your needs?

**Comment by Harini2019** [comment]
Thanks much !!

I believe that should be fine, I will definitely post if there is a need.
Thanks again for quick response.
